### PR TITLE
Fixed more compatibility with pokeemerald expansion

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Missed some stuff earlier

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by citrusbolt** [comment]
Does it make more sense to have preproc directives like this or to maintain another branch based on RHH's?  When Jaizu merged this into his project, other changes were brought over that I'm assuming were due to the expansion not being up to date with pret.

I'm also not sure if there's a better way we can manage the new/modified glyphs to not interfere with users that have already modified their fonts.  Thoughts on just adding a new font?

**Comment by AsparagusEduardo** [comment]
I think preproc directives are the better solution, seeing as there are soft conflicts between both BE and PE (the Vice/Vise Grip and `CreateMonIcon` situations for example), and it's not very mantainable to have a separate branch for each RHH branch combination that the user might want to use (eg. Summary + PE, Summary + BE, Summary + PE + BE).
I'll try to see if we can do a quick upstream merge for the RHH branches to help users out with this, as this summary branch looks to be very popular.

**Comment by AsparagusEduardo** [comment]
Alright, ready for review. Tested merging with both PE and BE, though the biggest conflict is indeed because it RHH is not up to date with pret. I made it so certain conflict sections would resolve correctly independent if the user chooses either side.
Eg:
image

**Comment by AsparagusEduardo** [comment]
Now, regarding the glyph/fonts, I think think there's much to do around that. I use WinMerge to compare changes between images, which I had to do when merging with TheXaman's HGSS Pokédex. Personally, as a public resource I wouldn't have had it designed to it needed the font pages.

**Comment by citrusbolt** [comment]
I could change the Shiny/Pokerus/Fateful Encounter/Nature icons into sprites, but there's also a couple letters changes in the small font for aesthetics and width purposes.

**Pull request merged**
